version: 0.0
os: linux # 여기는 window와 linux만 가능 ubuntu도 linux기반이라 linux작성
files:
  - source:  /
    destination: /home/ubuntu/action # codedeploy파일이 가져와서 실행되는 경로
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
