jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  token: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC

spring:
  datasource:
    url: jdbc:mysql://demae.c7w2ogow6rck.ap-northeast-2.rds.amazonaws.com:3306/demae
    username: admin
    password: Demae1101!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    hidden-method:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

cloud:
  aws:
    s3:
      bucket: lv05s3test # {버킷명}
    credentials:
      access-key: AKIAZI2LFR6JQ5CWR7E7 # s3할때 입력한 access-key
      secret-key: eGEuzTv40OBJEotPi2sT7JKiI9P2Moy9SGnGqI9o # s3할때 입력한 secret-key
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
