name: CI/CD # 1 깃허브 액션 이름 변경
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # 스탭의 이름을 지정
        uses: actions/checkout@v3
        # uses : 지정한 레파지토리를 확인하고 코드에 대한 작업을 실행할 수 있다
        # actions/check-out에는 checkout이라는 작업의 v3번전을 실행

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        #  run 키워드는 실행할 명령어를 입력
        # ./gradlew clean build에는 그레들을 사용해 프로젝트를 빌드 이전 상태로 돌리고 다시 빌드하는 명령어를 실행

      # 2 현재시간 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: "YYYY-MM-DDTHH-mm-ss"
          utcOffset: "+09:00"

      # 3 배포용 패키지 경로 저장
      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV
        # $GITHUB_ ENV를 사용해 깃허브 워크플로 전체적으로 사용할 수 있는 환경 변수를 설정할 수 있습니다.
        shell: bash

      - name: Show artifact
        run: echo "Artifact is ${{ env.artifact }}"
        shell: bash
        # 빌드 이후에 생성된 jar 파일을 찾아 “artifact”라는 환경 변수에 값을 넣어줍니다

      # 4 빈스토크 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        # einaregilsson/beanstalk-deploy 플러그인을 사용해 빈스토크 배포를 진행
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: demae-eb-springboot
          environment_name: demae-eb-springboot-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: ./build/libs/${{ env.artifact }}