name: deploy-onpremises

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy On-Premises configuration
        run: |
          echo "---
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
          iam_user_arn: arn:aws:iam::637423423379:role/githubactions
          region: $AWS_REGION" > codedeploy.onpremises.yml

#      - name: 구성 파일 생성 확인
#        run: cat codedeploy.onpremises.yml

          # 해당 파일은 자동으로 생기는게 아니기 때문에 생성해주기 부터 실행
      - name: 구성 파일을 올바른 디렉토리로 이동
        run: |
          sudo mkdir -p /etc/codedeploy-agent/conf/codedeploy.onpremises.yml
          sudo mv codedeploy.onpremises.yml /etc/codedeploy-agent/conf/

#      - name: Restart CodeDeploy Agent
#        run: sudo systemctl restart codedeploy-agent
